name: Make TWRP Device

on:
  workflow_dispatch:
    inputs:
      IMG_URL:    
        description: 'IMG_URL'
        required: true
<<<<<<< HEAD
        default: ''
=======
        default: 'https://github.com/momo54181/action_build_twrp_device_tree/blob/main/recovery.img'
>>>>>>> 0fe80aa4e4e2f5fa79a640404b59176cab2a1b9f

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    
    steps:
    - name: Check Out
      uses: actions/checkout@main
      
    - name: Prepare the environment
      run: |
        sudo apt update
<<<<<<< HEAD
        sudo apt -y install python3 python-pip python3-pip cpio wget
=======
        sudo apt -y install python python3 python-pip python3-pip cpio wget
      
    - name: Set variables
      run: |
        echo "name=date::$(date +%F)" >> $GITHUB_OUTPUT
      id: var
      
    - name: Install TWRP generator 
      run: |
>>>>>>> 0fe80aa4e4e2f5fa79a640404b59176cab2a1b9f
        pip3 install twrpdtgen
        mkdir dt
      
    - name: Download boot or recovery img
      run: |
        aria2c https://github.com/jiangCookies2547/action_build_twrp_device_tree/blob/main/boot.img
        ls
      
    - name: Start build
      run: |
        python3 -m twrpdtgen -o dt/ *.img
    - name: ZIP device tree
      run: |
        zip -r DeviceTree.zip ./dt
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./DeviceTree.zip
        name: TWRP_Device_Tree-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: DeviceTree for twrp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
